working-directory = inherit
custom-shader-animation = true
clipboard-read = allow
clipboard-write = allow
window-theme = system
window-padding-x = 25
window-padding-y = 25
window-padding-balance = true
theme = xcodedarkhc
bold-is-bright = true
background = #1f1f24
selection-background = #43454b
selection-foreground = #ffffff
cursor-color = #ffffff
cursor-text = #1f1f24
cursor-style-blink = true
palette = 0=#43454b
palette = 1=#ff8a7a
palette = 2=#83c9bc
palette = 3=#d9c668
palette = 4=#4ec4e6
palette = 5=#ff85b8
palette = 6=#cda1ff
palette = 7=#ffffff
palette = 8=#838991
palette = 9=#ff8a7a
palette = 10=#b1faeb
palette = 11=#ffa14f
palette = 12=#6bdfff
palette = 13=#ff85b8
palette = 14=#e5cfff
palette = 15=#ffffff
font-size = 12
font-thicken = true
font-family = scientifica
mouse-hide-while-typing = true
focus-follows-mouse = true
gtk-single-instance = false
macos-option-as-alt = left
